-- =====================================================================
-- DATOS INICIALES · La Mar de Gambas
-- Generado a partir de datos/menu-datos.json (precios de las cartas
-- físicas, pendientes de aprobación por escrito del local).
-- Ejecutar después de datos/esquema.sql.
-- =====================================================================

-- ---------------- PESTAÑAS (7) ----------------
insert into categories (id, name, sort_order, multi, fam, labs) values
  ('mar', 'MARISCO Y MAR', 1, true, 'tp', ARRAY['Tapa','Plato']),
  ('picar', 'PARA PICAR', 2, true, 'tp', ARRAY['Tapa','Plato']),
  ('fritos', 'FRITOS Y CROQUETAS', 3, true, 'tp', ARRAY['Tapa','Plato']),
  ('carne', 'CARNE Y ARROCES', 4, true, 'tp', ARRAY['Tapa','Plato']),
  ('panes', 'PANES', 5, true, 'tp', ARRAY['Tapa','Plato']),
  ('postres', 'POSTRES', 6, false, '', '{}'),
  ('bodega', 'BODEGA', 7, false, 'cb', ARRAY['Copa','Botella']);

-- ---------------- PRODUCTOS (105) ----------------
insert into products (id, category_id, name, display_name, description, size, only_size, section, price, featured, allergens, photo, sort_order) overriding system value values
  (1, 'mar', 'Media mariscada', NULL, '550 g aprox. · gambas, patas rusas, langostinos, cigalas y mejillones', NULL, false, 'MARISCO COCIDO', 20.00, false, NULL, '', 1),
  (2, 'mar', 'Gambas', NULL, '200 gr', NULL, false, 'MARISCO COCIDO', 7.50, false, NULL, '', 2),
  (3, 'mar', 'Langostinos', NULL, '200 gr', NULL, false, 'MARISCO COCIDO', 7.00, false, NULL, '', 3),
  (4, 'mar', 'Patas rusas', NULL, '200 gr', NULL, false, 'MARISCO COCIDO', 8.50, false, NULL, '', 4),
  (5, 'mar', 'Mejillones', NULL, '10 uds', NULL, false, 'MARISCO COCIDO', 7.00, false, NULL, '', 5),
  (6, 'mar', 'Cigalas', NULL, '5 uds', NULL, false, 'MARISCO COCIDO', 8.00, false, NULL, '', 6),
  (7, 'mar', 'Almejas con langostinos La Mar de Gambas (Plato)', 'Almejas con langostinos La Mar de Gambas', 'Plato', 'Plato', true, 'JOYAS DE NUESTRA LONJA', 10.00, false, NULL, '', 7),
  (8, 'mar', 'Pez espada a la plancha (Plato)', 'Pez espada a la plancha', 'Plato', 'Plato', true, 'JOYAS DE NUESTRA LONJA', 11.50, false, NULL, '', 8),
  (9, 'mar', 'Zamburiñas a la plancha', NULL, 'por unidad', NULL, false, 'JOYAS DE NUESTRA LONJA', 2.50, false, NULL, '', 9),
  (10, 'picar', 'Ensalada César (Plato)', 'Ensalada César', 'Plato', 'Plato', true, 'EL PICOTEO DEL PUERTO', 8.00, false, NULL, '', 10),
  (11, 'picar', 'Salmorejo con jamón y huevo (Plato)', 'Salmorejo con jamón y huevo', 'Plato', 'Plato', true, 'EL PICOTEO DEL PUERTO', 4.50, false, NULL, '', 11),
  (12, 'picar', 'Cóctel de marisco (Plato)', 'Cóctel de marisco', 'Plato', 'Plato', true, 'EL PICOTEO DEL PUERTO', 5.00, false, NULL, '', 12),
  (13, 'picar', 'Abrazo de tomate con melva (Plato)', 'Abrazo de tomate con melva', 'Plato', 'Plato', true, 'EL PICOTEO DEL PUERTO', 7.50, false, NULL, '', 13),
  (14, 'picar', 'Papas aliñás con melva (Tapa)', 'Papas aliñás con melva', '', 'Tapa', false, 'EL PICOTEO DEL PUERTO', 4.00, false, NULL, '', 14),
  (15, 'picar', 'Papas aliñás con melva (Plato)', 'Papas aliñás con melva', '', 'Plato', false, 'EL PICOTEO DEL PUERTO', 7.00, false, NULL, '', 15),
  (16, 'picar', 'Papas ali-oli (Tapa)', 'Papas ali-oli', '', 'Tapa', false, 'EL PICOTEO DEL PUERTO', 4.00, false, NULL, '', 16),
  (17, 'picar', 'Papas ali-oli (Plato)', 'Papas ali-oli', '', 'Plato', false, 'EL PICOTEO DEL PUERTO', 7.00, false, NULL, '', 17),
  (18, 'picar', 'Ensaladilla de marisco (Tapa)', 'Ensaladilla de marisco', '', 'Tapa', false, 'EL PICOTEO DEL PUERTO', 4.20, false, NULL, '', 18),
  (19, 'picar', 'Ensaladilla de marisco (Plato)', 'Ensaladilla de marisco', '', 'Plato', false, 'EL PICOTEO DEL PUERTO', 8.00, false, NULL, '', 19),
  (20, 'picar', 'Aliño de huevas (Tapa)', 'Aliño de huevas', '', 'Tapa', false, 'EL PICOTEO DEL PUERTO', 4.20, false, NULL, '', 20),
  (21, 'picar', 'Aliño de huevas (Plato)', 'Aliño de huevas', '', 'Plato', false, 'EL PICOTEO DEL PUERTO', 8.00, false, NULL, '', 21),
  (22, 'picar', 'Salpicón de marisco (Tapa)', 'Salpicón de marisco', '', 'Tapa', false, 'EL PICOTEO DEL PUERTO', 4.00, false, NULL, '', 22),
  (23, 'picar', 'Salpicón de marisco (Plato)', 'Salpicón de marisco', '', 'Plato', false, 'EL PICOTEO DEL PUERTO', 7.50, false, NULL, '', 23),
  (24, 'picar', 'Atún encebollao (Tapa)', 'Atún encebollao', '', 'Tapa', false, 'EL PICOTEO DEL PUERTO', 4.50, false, NULL, '', 24),
  (25, 'picar', 'Atún encebollao (Plato)', 'Atún encebollao', '', 'Plato', false, 'EL PICOTEO DEL PUERTO', 9.00, false, NULL, '', 25),
  (26, 'picar', 'Mojama extra (Plato)', 'Mojama extra', 'Plato · 80 gr', 'Plato', true, 'EL PICOTEO DEL PUERTO', 9.00, false, NULL, '', 26),
  (27, 'picar', 'Jamón 50% cebo', NULL, '60 gr · con regañá de bellota', NULL, false, 'DE CUCHILLO Y TABLA', 10.00, false, NULL, '', 27),
  (28, 'picar', 'Caña de lomo ibérica', NULL, '60 gr', NULL, false, 'DE CUCHILLO Y TABLA', 9.50, false, NULL, '', 28),
  (29, 'picar', 'Carne mechá', NULL, '', NULL, false, 'DE CUCHILLO Y TABLA', 6.50, false, NULL, '', 29),
  (30, 'picar', 'Chicharrón de Cádiz', NULL, '', NULL, false, 'DE CUCHILLO Y TABLA', 6.50, false, NULL, '', 30),
  (31, 'picar', 'Queso Apolonio (Tapa)', 'Queso Apolonio', '60 gr', 'Tapa', false, 'DE CUCHILLO Y TABLA', 4.80, false, NULL, '', 31),
  (32, 'picar', 'Queso Apolonio (Plato)', 'Queso Apolonio', '150 gr', 'Plato', false, 'DE CUCHILLO Y TABLA', 9.00, false, NULL, '', 32),
  (33, 'picar', 'Tabla de quesos (Tapa)', 'Tabla de quesos', 'Tapa · curado, trufa y picante · 85 gr', 'Tapa', true, 'DE CUCHILLO Y TABLA', 9.00, false, NULL, '', 33),
  (34, 'fritos', 'Pimentada de gambas de cristal (Plato)', 'Pimentada de gambas de cristal', 'Plato · con dos huevos fritos', 'Plato', true, 'REBOZADOS DEL PUERTO', 9.50, false, NULL, '', 34),
  (35, 'fritos', 'Croquetas de caña de lomo (Tapa)', 'Croquetas de caña de lomo', '3 uds', 'Tapa', false, 'REBOZADOS DEL PUERTO', 4.20, false, NULL, '', 35),
  (36, 'fritos', 'Croquetas de caña de lomo (Plato)', 'Croquetas de caña de lomo', '6 uds', 'Plato', false, 'REBOZADOS DEL PUERTO', 8.50, false, NULL, '', 36),
  (37, 'fritos', 'Croquetas de gambas al ajillo (Tapa)', 'Croquetas de gambas al ajillo', '3 uds', 'Tapa', false, 'REBOZADOS DEL PUERTO', 4.20, false, NULL, '', 37),
  (38, 'fritos', 'Croquetas de gambas al ajillo (Plato)', 'Croquetas de gambas al ajillo', '6 uds', 'Plato', false, 'REBOZADOS DEL PUERTO', 8.50, false, NULL, '', 38),
  (39, 'fritos', 'Croquetas de puchero (Tapa)', 'Croquetas de puchero', '3 uds', 'Tapa', false, 'REBOZADOS DEL PUERTO', 4.20, false, NULL, '', 39),
  (40, 'fritos', 'Croquetas de puchero (Plato)', 'Croquetas de puchero', '6 uds', 'Plato', false, 'REBOZADOS DEL PUERTO', 8.50, false, NULL, '', 40),
  (41, 'fritos', 'Croquetas de rulo de cabra con cebolla caramelizada (Tapa)', 'Croquetas de rulo de cabra con cebolla caramelizada', '3 uds', 'Tapa', false, 'REBOZADOS DEL PUERTO', 4.20, false, NULL, '', 41),
  (42, 'fritos', 'Croquetas de rulo de cabra con cebolla caramelizada (Plato)', 'Croquetas de rulo de cabra con cebolla caramelizada', '6 uds', 'Plato', false, 'REBOZADOS DEL PUERTO', 8.50, false, NULL, '', 42),
  (43, 'fritos', 'Surtido de croquetas (Plato)', 'Surtido de croquetas', 'Plato · 8 uds', 'Plato', true, 'REBOZADOS DEL PUERTO', 10.00, false, NULL, '', 43),
  (44, 'fritos', 'Finger de pollo cajún crujiente (Tapa)', 'Finger de pollo cajún crujiente', 'salsa a elegir', 'Tapa', false, 'REBOZADOS DEL PUERTO', 5.00, false, NULL, '', 44),
  (45, 'fritos', 'Finger de pollo cajún crujiente (Plato)', 'Finger de pollo cajún crujiente', 'salsa a elegir', 'Plato', false, 'REBOZADOS DEL PUERTO', 8.50, false, NULL, '', 45),
  (46, 'fritos', 'Adobo frito (Tapa)', 'Adobo frito', '', 'Tapa', false, 'EL ARTE DEL FRITO ANDALUZ', 4.00, false, NULL, '', 46),
  (47, 'fritos', 'Adobo frito (Plato)', 'Adobo frito', '', 'Plato', false, 'EL ARTE DEL FRITO ANDALUZ', 7.50, false, NULL, '', 47),
  (48, 'fritos', 'Chocos fritos (Tapa)', 'Chocos fritos', '', 'Tapa', false, 'EL ARTE DEL FRITO ANDALUZ', 5.00, false, NULL, '', 48),
  (49, 'fritos', 'Chocos fritos (Plato)', 'Chocos fritos', '', 'Plato', false, 'EL ARTE DEL FRITO ANDALUZ', 9.50, false, NULL, '', 49),
  (50, 'fritos', 'Boquerones fritos (Tapa)', 'Boquerones fritos', '', 'Tapa', false, 'EL ARTE DEL FRITO ANDALUZ', 4.20, false, NULL, '', 50),
  (51, 'fritos', 'Boquerones fritos (Plato)', 'Boquerones fritos', '', 'Plato', false, 'EL ARTE DEL FRITO ANDALUZ', 8.00, false, NULL, '', 51),
  (52, 'fritos', 'Tortillita de camarones', NULL, 'por unidad', NULL, false, 'EL ARTE DEL FRITO ANDALUZ', 2.00, false, NULL, '', 52),
  (53, 'carne', 'Pinchito de pollo (Tapa)', 'Pinchito de pollo', 'Tapa', 'Tapa', true, 'BOCADOS DE LA DEHESA', 4.20, false, NULL, '', 53),
  (54, 'carne', 'Presa ibérica (Plato)', 'Presa ibérica', 'Plato', 'Plato', true, 'BOCADOS DE LA DEHESA', 10.50, false, NULL, '', 54),
  (55, 'carne', 'Secreto ibérico (Plato)', 'Secreto ibérico', 'Plato', 'Plato', true, 'BOCADOS DE LA DEHESA', 9.50, false, NULL, '', 55),
  (56, 'carne', 'Cachitos ibéricos (Plato)', 'Cachitos ibéricos', 'Plato · salsa mojo picón', 'Plato', true, 'BOCADOS DE LA DEHESA', 8.50, false, NULL, '', 56),
  (57, 'carne', 'Solomillo de cerdo (Tapa)', 'Solomillo de cerdo', 'salsa a elegir', 'Tapa', false, 'BOCADOS DE LA DEHESA', 4.00, false, NULL, '', 57),
  (58, 'carne', 'Solomillo de cerdo (Plato)', 'Solomillo de cerdo', 'salsa a elegir', 'Plato', false, 'BOCADOS DE LA DEHESA', 7.50, false, NULL, '', 58),
  (59, 'carne', 'Arroz mixto (Tapa)', 'Arroz mixto', 'pollo, marisco y verduras', 'Tapa', false, 'LA ARROCERÍA', 4.50, false, NULL, '', 59),
  (60, 'carne', 'Arroz mixto (Plato)', 'Arroz mixto', 'pollo, marisco y verduras', 'Plato', false, 'LA ARROCERÍA', 8.50, false, NULL, '', 60),
  (61, 'carne', 'Arroz negro (Tapa)', 'Arroz negro', 'chipirones, gambas y ali-oli', 'Tapa', false, 'LA ARROCERÍA', 4.50, false, NULL, '', 61),
  (62, 'carne', 'Arroz negro (Plato)', 'Arroz negro', 'chipirones, gambas y ali-oli', 'Plato', false, 'LA ARROCERÍA', 8.50, false, NULL, '', 62),
  (63, 'carne', 'Arroz del señorito (Tapa)', 'Arroz del señorito', 'gambas, calamares y pescado', 'Tapa', false, 'LA ARROCERÍA', 4.50, false, NULL, '', 63),
  (64, 'carne', 'Arroz del señorito (Plato)', 'Arroz del señorito', 'gambas, calamares y pescado', 'Plato', false, 'LA ARROCERÍA', 8.50, false, NULL, '', 64),
  (65, 'carne', 'Patatas para dipear', NULL, 'elige tu salsa', NULL, false, 'LA ARROCERÍA', 4.00, false, NULL, '', 65),
  (66, 'panes', 'Pan con chicharrón de Cádiz y mojo picón (Plato)', 'Pan con chicharrón de Cádiz y mojo picón', 'Plato', 'Plato', true, 'REBANADA DE PUEBLO', 8.50, false, NULL, '', 66),
  (67, 'panes', 'Pan con salmorejo y mojama (Plato)', 'Pan con salmorejo y mojama', 'Plato', 'Plato', true, 'REBANADA DE PUEBLO', 10.00, false, NULL, '', 67),
  (68, 'panes', 'Pan con salmorejo y jamón (Plato)', 'Pan con salmorejo y jamón', 'Plato', 'Plato', true, 'REBANADA DE PUEBLO', 10.00, false, NULL, '', 68),
  (69, 'panes', 'Pan con carne mechá y mojo picón (Plato)', 'Pan con carne mechá y mojo picón', 'Plato', 'Plato', true, 'REBANADA DE PUEBLO', 8.50, false, NULL, '', 69),
  (70, 'panes', 'Serranito de pollo o lomo', NULL, 'jamón, pimiento frito y tomate', NULL, false, 'BOCATITAS EN PAN DE CRISTAL', 6.00, false, NULL, '', 70),
  (71, 'panes', 'Piripi', NULL, 'lomo adobado, beicon, queso semicurado y ali-oli', NULL, false, 'BOCATITAS EN PAN DE CRISTAL', 5.50, false, NULL, '', 71),
  (72, 'panes', 'Pollo empanado', NULL, 'con lechuga y mayonesa', NULL, false, 'BOCATITAS EN PAN DE CRISTAL', 6.00, false, NULL, '', 72),
  (73, 'panes', 'Mantecaíto La Mar de Gambas', NULL, 'langostino, ali-oli y patatas fritas', NULL, false, 'BOCATITAS EN PAN DE CRISTAL', 5.50, false, NULL, '', 73),
  (74, 'panes', 'El Puerto', NULL, 'calamares fritos y ali-oli', NULL, false, 'BOCATITAS EN PAN DE CRISTAL', 5.50, false, NULL, '', 74),
  (75, 'panes', 'Filete de lomo con mojo picón', NULL, '', NULL, false, 'MONTADITOS', 4.00, false, NULL, '', 75),
  (76, 'panes', 'Filete de pollo con ali-oli', NULL, '', NULL, false, 'MONTADITOS', 4.00, false, NULL, '', 76),
  (77, 'panes', 'Melva con pimientos del piquillo y mayonesa', NULL, '', NULL, false, 'MONTADITOS', 4.00, false, NULL, '', 77),
  (78, 'panes', 'Lomo con crema de queso y cebolla caramelizada', NULL, '', NULL, false, 'MONTADITOS', 4.00, false, NULL, '', 78),
  (79, 'panes', 'Chorizo picante con crema de queso', NULL, '', NULL, false, 'MONTADITOS', 4.00, false, NULL, '', 79),
  (80, 'panes', 'Pringá casera', NULL, '', NULL, false, 'MONTADITOS', 4.00, false, NULL, '', 80),
  (81, 'postres', 'Perfecto de turrón', NULL, 'helado caliente con gelatina de turrón y crocanti de almendra', NULL, false, 'EL MEJOR FINAL', 4.95, false, NULL, '', 81),
  (82, 'postres', 'Tocino de cielo, nata y nueces', NULL, '', NULL, false, 'EL MEJOR FINAL', 4.95, false, NULL, '', 82),
  (83, 'postres', 'Ricotta y frutas del bosque', NULL, '', NULL, false, 'EL MEJOR FINAL', 4.95, false, NULL, '', 83),
  (84, 'postres', 'Chocolate tres texturas', NULL, '', NULL, false, 'EL MEJOR FINAL', 4.95, false, NULL, '', 84),
  (85, 'postres', 'Arroz con leche', NULL, 'nuevo · por unidad', NULL, false, 'EL MEJOR FINAL', 3.50, false, NULL, '', 85),
  (86, 'postres', 'Tocino de cielo', NULL, 'nuevo · por unidad', NULL, false, 'EL MEJOR FINAL', 4.00, false, NULL, '', 86),
  (87, 'bodega', 'Añares Crianza (Copa)', 'Añares Crianza', 'tinto D.O. Rioja', 'Copa', false, 'LA BODEGA', 2.60, false, NULL, '', 87),
  (88, 'bodega', 'Añares Crianza (Botella)', 'Añares Crianza', 'tinto D.O. Rioja', 'Botella', false, 'LA BODEGA', 13.50, false, NULL, '', 88),
  (89, 'bodega', 'Protos Roble (Copa)', 'Protos Roble', 'tinto D.O. Ribera del Duero', 'Copa', false, 'LA BODEGA', 3.70, false, NULL, '', 89),
  (90, 'bodega', 'Protos Roble (Botella)', 'Protos Roble', 'tinto D.O. Ribera del Duero', 'Botella', false, 'LA BODEGA', 17.50, false, NULL, '', 90),
  (91, 'bodega', 'Maestrante (Copa)', 'Maestrante', 'blanco semidulce', 'Copa', false, 'LA BODEGA', 2.70, false, NULL, '', 91),
  (92, 'bodega', 'Maestrante (Botella)', 'Maestrante', 'blanco semidulce', 'Botella', false, 'LA BODEGA', 13.00, false, NULL, '', 92),
  (93, 'bodega', 'Castillo de San Diego (Copa)', 'Castillo de San Diego', 'blanco semiseco', 'Copa', false, 'LA BODEGA', 2.70, false, NULL, '', 93),
  (94, 'bodega', 'Castillo de San Diego (Botella)', 'Castillo de San Diego', 'blanco semiseco', 'Botella', false, 'LA BODEGA', 13.00, false, NULL, '', 94),
  (95, 'bodega', 'Alberto Sanz (Copa)', 'Alberto Sanz', 'blanco D.O. Rueda', 'Copa', false, 'LA BODEGA', 2.30, false, NULL, '', 95),
  (96, 'bodega', 'Alberto Sanz (Botella)', 'Alberto Sanz', 'blanco D.O. Rueda', 'Botella', false, 'LA BODEGA', 11.00, false, NULL, '', 96),
  (97, 'bodega', 'Barbadillo VI (Copa)', 'Barbadillo VI', 'frizzante', 'Copa', false, 'LA BODEGA', 3.10, false, NULL, '', 97),
  (98, 'bodega', 'Barbadillo VI (Botella)', 'Barbadillo VI', 'frizzante', 'Botella', false, 'LA BODEGA', 15.00, false, NULL, '', 98),
  (99, 'bodega', 'Alba Martín (Copa)', 'Alba Martín', 'albariño D.O.', 'Copa', false, 'LA BODEGA', 3.70, false, NULL, '', 99),
  (100, 'bodega', 'Alba Martín (Botella)', 'Alba Martín', 'albariño D.O.', 'Botella', false, 'LA BODEGA', 18.00, false, NULL, '', 100),
  (101, 'bodega', 'Heredad Hidalgo Oloroso (Copa)', 'Heredad Hidalgo Oloroso', 'Copa · generoso', 'Copa', true, 'LA BODEGA', 2.10, false, NULL, '', 101),
  (102, 'bodega', 'Sol Málaga (Copa)', 'Sol Málaga', 'Copa · vino dulce', 'Copa', true, 'LA BODEGA', 2.30, false, NULL, '', 102),
  (103, 'bodega', 'La Gabriela (Copa)', 'La Gabriela', 'manzanilla', 'Copa', false, 'LA BODEGA', 2.70, false, NULL, '', 103),
  (104, 'bodega', 'La Gabriela (Botella)', 'La Gabriela', 'manzanilla', 'Botella', false, 'LA BODEGA', 16.00, false, NULL, '', 104),
  (105, 'bodega', 'Izaguirre Rojo (Copa)', 'Izaguirre Rojo', 'Copa · vermouth', 'Copa', true, 'LA BODEGA', 3.80, false, NULL, '', 105);
-- Los productos nuevos que cree el admin seguirán a partir del 106.
select setval(pg_get_serial_sequence('products','id'), (select max(id) from products));

-- ---------------- MESAS DE EJEMPLO (1 a 10) ----------------
-- Hipotéticas hasta tener las reales del local. El código secreto de
-- cada QR lo genera la base al crear la mesa (no está en este archivo).
insert into mesas (id, name)
select n, 'Mesa ' || n from generate_series(1, 10) as n;
