-- =====================================================================
-- ESQUEMA DE LA BASE DE DATOS · La Mar de Gambas
-- ---------------------------------------------------------------------
-- Proyecto Neon "la-mar-de-gambas" (Frankfurt), separado de El Recreo.
-- Este archivo crea las tablas desde cero. Para recrear la base en otro
-- sitio (por ejemplo Supabase) se ejecuta en este orden:
--   1. datos/esquema.sql           (tablas, este archivo)
--   2. datos/datos-iniciales.sql   (pestañas, 105 productos y mesas)
--   3. datos/seguridad.sql         (permisos y reglas por rol, Fase 3)
--
-- Seguridad: todas las tablas nacen con seguridad por fila (RLS) activada
-- y sin ningún permiso para el público. Hasta que se aplique
-- seguridad.sql, nadie puede leer ni escribir nada desde la web.
--
-- No se guardan datos personales de clientes: un pedido solo lleva la
-- mesa y una "clave de dispositivo" al azar que genera el móvil.
--
-- Tras cambiar el esquema, esperar 30–60 s antes de probar desde la web
-- (la Data API tarda en enterarse de los cambios).
-- =====================================================================

-- ---------------- PESTAÑAS DE LA CARTA ----------------
create table categories (
  id          text primary key,                -- 'mar', 'picar', 'bodega'…
  name        text not null,                   -- 'MARISCO Y MAR'
  sort_order  integer not null default 0,
  multi       boolean not null default false,  -- agrupa varias secciones de la carta física
  fam         text not null default '',        -- 'tp' = Tapa/Plato, 'cb' = Copa/Botella
  labs        text[] not null default '{}'     -- tamaños que usa la pestaña
);

-- ---------------- PRODUCTOS ----------------
-- Cada tamaño es una fila propia (Croquetas Tapa y Croquetas Plato son
-- dos productos con su precio), igual que en la carta.
create table products (
  id            integer generated by default as identity primary key,
  category_id   text not null references categories(id),
  name          text not null,                 -- nombre con tamaño: 'Croquetas de puchero (Tapa)'
  display_name  text,                          -- nombre sin tamaño para agrupar: 'Croquetas de puchero'
  description   text not null default '',      -- '200 gr', '5 uds'…
  size          text check (size in ('Tapa','Plato','Copa','Botella')),
  only_size     boolean not null default false, -- solo existe en ese tamaño
  section       text not null default '',      -- sección original de la carta física
  price         numeric(7,2) not null check (price >= 0 and price < 1000),
  available     boolean not null default true,  -- false = AGOTADO (lo cambia barra o admin)
  visible       boolean not null default true,  -- false = no sale en la carta (lo cambia admin)
  featured      boolean not null default false, -- estrella "lo mejor de la casa"
  allergens     text[],                         -- pendiente: lista del local
  photo         text not null default '',
  sort_order    integer not null default 0,
  updated_at    timestamptz not null default now(),
  updated_by    text                            -- usuario del personal que lo cambió
);
create index products_category_idx on products (category_id, sort_order);

-- ---------------- MESAS ----------------
-- "code" es el código secreto que va en el QR de cada mesa
-- (/carta/?mesa=5&c=CODIGO). La base solo acepta pedidos si coincide.
-- Si se cambia, hay que reimprimir el QR de esa mesa.
-- Los códigos NO se guardan en el repositorio: los genera la base.
create table mesas (
  id          integer primary key check (id between 1 and 999),  -- número de mesa
  name        text not null,                   -- 'Mesa 5', 'Terraza 2'…
  active      boolean not null default true,   -- false = no admite pedidos
  code        text not null default substr(replace(gen_random_uuid()::text, '-', ''), 1, 8),
  created_at  timestamptz not null default now()
);

-- ---------------- PEDIDOS ----------------
-- Estados: enviado (NUEVO: lo manda el cliente) → en_preparacion (lo acepta
-- el personal, o solo a los 3 minutos si nadie lo acepta) → servido.
-- "Deshacer" vuelve un paso atrás.
create table orders (
  id            bigint generated always as identity primary key,
  mesa_id       integer not null references mesas(id),
  round_number  integer not null default 1,     -- "Pedido 1, 2…" de ese móvil
  status        text not null default 'enviado'
                check (status in ('enviado','en_preparacion','servido')),
  total         numeric(8,2) not null default 0 check (total >= 0),
  device_key    uuid not null,                  -- número al azar del móvil (no es dato personal)
  created_at    timestamptz not null default now(),
  modified_at   timestamptz,                    -- última edición del cliente
  nuevo_desde   timestamptz not null default now(), -- desde cuándo está NUEVO (cuenta 3 min)
  auto_aceptado boolean not null default false,  -- pasó solo a preparación (nadie lo aceptó)
  received_at   timestamptz,                    -- cuándo pasó a "en preparación"
  received_by   text,                           -- quién lo aceptó
  served_at     timestamptz,
  served_by     text
);
create index orders_status_idx on orders (status, created_at);
create index orders_mesa_idx   on orders (mesa_id, created_at);
create index orders_device_idx on orders (device_key, created_at);
create index orders_created_idx on orders (created_at);

-- ---------------- LÍNEAS DE CADA PEDIDO ----------------
-- Se copian nombre, tamaño y precio en el momento del pedido, para que
-- un cambio de precio posterior no altere pedidos ya hechos.
create table order_items (
  id            bigint generated always as identity primary key,
  order_id      bigint not null references orders(id) on delete cascade,
  product_id    integer not null references products(id),
  product_name  text not null,
  size          text,
  unit_price    numeric(7,2) not null check (unit_price >= 0),
  quantity      integer not null check (quantity between 0 and 20), -- 0 = quitado por el personal (se ve en gris)
  note          text not null default '' check (char_length(note) <= 140)
);
create index order_items_order_idx on order_items (order_id);

-- ---------------- PERSONAL (usuarios y roles) ----------------
-- Camareros, barra y administradores. La contraseña se guarda cifrada
-- (bcrypt, nunca en claro). Un usuario con active = false no puede entrar.
-- El login es propio de la base (no usa cookies), para que funcione
-- igual en iPhone (Safari) y Android: ver datos/seguridad.sql.
create table staff (
  id                    integer generated always as identity primary key,
  email                 text not null,
  name                  text not null,
  role                  text not null check (role in ('camarero','barra','admin')),
  active                boolean not null default true,
  password_hash         text not null,
  must_change_password  boolean not null default true,  -- contraseña provisional
  failed_attempts       integer not null default 0,      -- intentos fallidos seguidos
  locked_until          timestamptz,                     -- bloqueo tras 5 fallos
  created_at            timestamptz not null default now()
);
create unique index staff_email_idx on staff (lower(email));

-- ---------------- SEGURIDAD BÁSICA (hasta la Fase 3) ----------------
-- Seguridad por fila activada en todas las tablas y ningún permiso para
-- la web. Los permisos por rol se dan en datos/seguridad.sql.
alter table categories  enable row level security;
alter table products    enable row level security;
alter table mesas       enable row level security;
alter table orders      enable row level security;
alter table order_items enable row level security;
alter table staff       enable row level security;

revoke all on categories, products, mesas, orders, order_items, staff
  from public, anonymous, authenticated;
